-- MySQL Script generated by MySQL Workbench
-- 05/05/16 17:32:38
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tienda2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda2` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `tienda2` ;

-- -----------------------------------------------------
-- Table `tienda2`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`categoria` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_categoria` VARCHAR(20) NULL DEFAULT NULL,
  `nombre_cat` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `mostrar` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `cod_categoria_UNIQUE` ON `tienda2`.`categoria` (`cod_categoria` ASC);


-- -----------------------------------------------------
-- Table `tienda2`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`producto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `idCategoria` INT(11) NOT NULL,
  `cod_producto` VARCHAR(20) NULL,
  `nombre_pro` VARCHAR(100) NULL DEFAULT NULL,
  `precio` DECIMAL(7,2) NULL DEFAULT NULL,
  `descuento` DECIMAL(5,2) NULL DEFAULT NULL,
  `imagen` VARCHAR(250) NULL DEFAULT NULL,
  `iva` DECIMAL(5,2) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `seleccionado` TINYINT(1) NULL DEFAULT NULL,
  `mostrar` TINYINT(1) NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_Camiseta_Categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `tienda2`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `codigo_cam_UNIQUE` ON `tienda2`.`producto` (`cod_producto` ASC);

CREATE INDEX `fk_Producto_Categoria_idx` ON `tienda2`.`producto` (`idCategoria` ASC);


-- -----------------------------------------------------
-- Table `tienda2`.`linea_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`linea_pedido` (
  `id_LineaPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `idPedido` INT(11) NOT NULL,
  `idProducto` INT(11) NOT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `precio` DECIMAL(5,2) NULL DEFAULT NULL,
  `importe` DECIMAL(20,2) NULL,
  `iva` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_LineaPedido`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Venta_has_Producto_Producto1_idx` ON `tienda2`.`linea_pedido` (`idProducto` ASC);

CREATE INDEX `fk_Linea_Pedido_Pedido1_idx` ON `tienda2`.`linea_pedido` (`idPedido` ASC);


-- -----------------------------------------------------
-- Table `tienda2`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`provincias` (
  `cod` CHAR(2) NOT NULL DEFAULT '00' COMMENT 'Código de la provincia de dos digitos',
  `nombre` VARCHAR(50) NULL DEFAULT '' COMMENT 'Nombre de la provincia',
  `comunidad_id` TINYINT(4) NULL DEFAULT NULL COMMENT 'Código de la comunidad a la que pertenece',
  PRIMARY KEY (`cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Provincias de españa; 99 para seleccionar a Nacional';

CREATE INDEX `nombre` ON `tienda2`.`provincias` (`nombre` ASC);

CREATE INDEX `FK_ComunidadAutonomaProv` ON `tienda2`.`provincias` (`comunidad_id` ASC);


-- -----------------------------------------------------
-- Table `tienda2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_provincia` CHAR(2) NOT NULL,
  `nombre_usu` VARCHAR(30) NULL DEFAULT NULL,
  `clave` VARCHAR(260) NULL DEFAULT NULL,
  `dni` VARCHAR(10) NULL DEFAULT NULL,
  `correo` VARCHAR(180) NULL DEFAULT NULL,
  `nombre_persona` VARCHAR(40) NULL DEFAULT NULL,
  `apellidos_persona` VARCHAR(60) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `cp` INT(11) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT 'A',
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Usuario_tbl_provincias1`
    FOREIGN KEY (`cod_provincia`)
    REFERENCES `tienda2`.`provincias` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `nombre_usu_UNIQUE` ON `tienda2`.`usuario` (`nombre_usu` ASC);

CREATE INDEX `fk_Usuario_tbl_provincias1_idx` ON `tienda2`.`usuario` (`cod_provincia` ASC);


-- -----------------------------------------------------
-- Table `tienda2`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda2`.`pedido` (
  `idPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuario` INT(11) NOT NULL,
  `importe` DECIMAL(10,2) NULL DEFAULT NULL,
  `cantidad_total` INT(11) NULL DEFAULT NULL,
  `estado` VARCHAR(10) NULL DEFAULT 'Pendiente',
  `fecha_pedido` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `cp` INT(11) NULL DEFAULT NULL,
  `cod_provincia` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`idPedido`),
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tienda2`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Pedido_Usuario1_idx` ON `tienda2`.`pedido` (`idUsuario` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

